name: curupas
description: Curupas App project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dart_style: ^1.3.6
  cloud_firestore: ^0.13.5
  cloud_functions: ^0.4.1+6
  firebase_auth: ^0.15.3
  firebase_storage: ^3.1.0
  firebase_database: ^3.1.1
  firebase_messaging: ^6.0.13
  firebase_analytics: ^5.0.9
  firebase_crashlytics: ^0.1.2+4
  flutter_facebook_login: ^3.0.0
  shared_preferences: ^0.5.7+2
  flutter_swiper: ^1.1.6
  file_picker: ^1.6.3+2
  flutter_datetime_picker: ^1.3.8
  intl: ^0.15.8
  notifier: ^1.0.2
  cached_network_image: ^2.0.0-rc
  youtube_api: ^0.7.2
  youtube_player_flutter: ^6.1.1
  fancy_bottom_navigation: ^0.3.2
  keyboard_actions: ^2.1.2
  flutter_keyboard_visibility: ^2.0.0
  flutter_speed_dial: ^1.2.1
  flutter_screenutil: ^0.5.3
  flutter_launcher_icons: ^0.7.5
  zefyr: ^0.8.0
  notus: ^0.1.4
  path_provider: ^1.6.11
  diacritic: ^0.1.1
  url_launcher: ^5.1.6
  location: ^2.3.5
  geolocator: ^5.3.1
  photo_view: ^0.9.0
  circular_profile_avatar: ^1.0.6
  #flutter_webview_plugin: 0.3.0+2
  #webview_flutter: ^0.3.21
  device_info: ^0.4.2+1
  datetime_picker_formfield: ^0.1.8
  flutter_staggered_grid_view: ^0.3.0
  mime: ^0.9.6+3
  video_thumbnail: ^0.2.0
  event_bus: ^1.1.1
  firebase_dynamic_links: ^0.5.0+8
  mercadopago_sdk: ^1.1.3
  flutter_credit_card: ^0.1.3
  flutter_spinkit: ^4.1.2
  #flutter_svg: ^0.18.0
  flutter_svg: ^0.17.1
  image_picker: ^0.6.0+10
  path:
  flutter_calendar_carousel: ^1.4.12
  video_player: ^0.10.11+2
  chewie: ^0.9.10
  fluttertoast: ^3.1.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

flutter_icons:
  ios: true
  android: true
  image_path_android: "assets/images/icon-710x599-android.png"
  image_path_ios: "assets/images/icon-710x599-ios.png"
  adaptive_icon_background: "#ffffff"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/html/drawer_base.html
    - assets/images/default.png
    - assets/images/escudo.png
    - assets/images/curupa_anexo.png
    - assets/images/cancha.png
    - assets/images/test.png
    - assets/images/camadas.png
    - assets/images/not_available.png
    - assets/images/icon-710x599-android.png
    - assets/images/icon-710x599-ios.png
    - assets/images/pelota_small.png
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/5.png
    - assets/images/6.png
    - assets/images/7.png
    - assets/images/8.png
    - assets/images/9.png
    - assets/images/10.png
    - assets/images/11.png
    - assets/images/12.png
    - assets/images/group_backgrnd.png