name: curupas
description: Aplicación de Curupayti

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #https://firebase.flutter.dev/docs/migration/

  firebase_core: "^0.7.0"
  # Newly reworked plugins covered by this migration guide:
  firebase_auth: "^0.20.0+1"
  firebase_crashlytics: "^0.4.0+1"
  cloud_firestore: "^0.16.0"
  cloud_functions: "^0.9.0"
  firebase_storage: "^7.0.0"
  firebase_messaging: "^8.0.0-dev.14"
  flutter_local_notifications: "^3.0.3"
  #firebase_messaging: "^7.3.0"

  # Updated to work with new core only plugins (no new changes):
  #firebase_admob: "^0.11.0+1"
  firebase_analytics: "^7.0.1"
  firebase_database: "^6.0.0"
  firebase_dynamic_links: "^0.7.0+1"
  firebase_in_app_messaging: "^0.3.0+1"
  firebase_performance: "^0.5.0+1"

  dart_style: "^1.3.1"
  shared_preferences: "^0.5.12+4"
  file_picker: "^2.1.5+1"

  flutter_swiper: "^1.1.6"

  flutter_datetime_picker:
    git:
      url: "https://github.com/espresso3389/flutter_datetime_picker"

  flutter_keyboard_visibility: "^4.0.0"
  flutter_speed_dial: "^1.2.5"
  flutter_screenutil: "^4.0.2+5"
  flutter_spinkit: "^4.1.2"
  flutter_staggered_grid_view: "^0.3.3"
  flutter_credit_card: "^0.1.4"
  flutter_svg: "^0.19.1"

  cached_network_image: "^2.5.0"
  fancy_bottom_navigation: "^0.3.2"
  keyboard_actions: "^3.3.1+1"
  image_picker: "^0.6.7+2"
  youtube_player_flutter: "^7.0.0+7"
  image_cropper: "^1.3.1"
  fluttertoast: "^7.1.6"

  notifier:
    git: "git://github.com/wanosoft/notifier.git"

  diacritic: "^0.1.1"
  event_bus: "^1.1.1"
  url_launcher: "^5.7.10"
  video_thumbnail: "^0.2.5+1"
  location: "^3.2.1"
  device_info: "^1.0.0"
  chewie: "^0.12.1+1"
  photo_view: "^0.10.3"
  video_player: "^1.0.1"
  circular_profile_avatar: "^1.0.8"
  webview_flutter: "^1.0.7"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: "^1.0.2"

dev_dependencies:
  flutter_test:
    sdk: flutter
  #integration_test:
    #sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/html/drawer_base.html
    - assets/images/default.png
    - assets/images/escudo.png
    - assets/images/curupa_anexo.png
    - assets/images/cancha.png
    - assets/images/test.png
    - assets/images/camadas.png
    - assets/images/notimation.png
    - assets/images/not_available.png
    - assets/images/icon-710x599-android.png
    - assets/images/icon-710x599-ios.png
    - assets/images/pelota_small.png
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/5.png
    - assets/images/6.png
    - assets/images/7.png
    - assets/images/8.png
    - assets/images/9.png
    - assets/images/10.png
    - assets/images/11.png
    - assets/images/12.png
    - assets/images/group_backgrnd.png

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
